/**
 * defaultTitle
 * defaultDescription
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.example.jobseeker.network.swagger.client.model;

import java.util.Date;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class Job {
  
  @SerializedName("id")
  private String id = null;
  @SerializedName("type")
  private String type = null;
  @SerializedName("url")
  private String url = null;
  @SerializedName("created_at")
  private Date createdAt = null;
  @SerializedName("company")
  private String company = null;
  @SerializedName("company_url")
  private String companyUrl = null;
  @SerializedName("location")
  private String location = null;
  @SerializedName("title")
  private String title = null;
  @SerializedName("description")
  private String description = null;
  @SerializedName("how_to_apply")
  private String howToApply = null;
  @SerializedName("company_logo")
  private String companyLogo = null;

  public Job(String id, String type, String url, Date createdAt, String company, String companyUrl, String location, String title, String description, String howToApply, String companyLogo) {
    this.id = id;
    this.type = type;
    this.url = url;
    this.createdAt = createdAt;
    this.company = company;
    this.companyUrl = companyUrl;
    this.location = location;
    this.title = title;
    this.description = description;
    this.howToApply = howToApply;
    this.companyLogo = companyLogo;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }
  public void setId(String id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getType() {
    return type;
  }
  public void setType(String type) {
    this.type = type;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getUrl() {
    return url;
  }
  public void setUrl(String url) {
    this.url = url;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Date getCreatedAt() {
    return createdAt;
  }
  public void setCreatedAt(Date createdAt) {
    this.createdAt = createdAt;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getCompany() {
    return company;
  }
  public void setCompany(String company) {
    this.company = company;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getCompanyUrl() {
    return companyUrl;
  }
  public void setCompanyUrl(String companyUrl) {
    this.companyUrl = companyUrl;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getLocation() {
    return location;
  }
  public void setLocation(String location) {
    this.location = location;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getTitle() {
    return title;
  }
  public void setTitle(String title) {
    this.title = title;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getDescription() {
    return description;
  }
  public void setDescription(String description) {
    this.description = description;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getHowToApply() {
    return howToApply;
  }
  public void setHowToApply(String howToApply) {
    this.howToApply = howToApply;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getCompanyLogo() {
    return companyLogo;
  }
  public void setCompanyLogo(String companyLogo) {
    this.companyLogo = companyLogo;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Job job = (Job) o;
    return (this.id == null ? job.id == null : this.id.equals(job.id)) &&
        (this.type == null ? job.type == null : this.type.equals(job.type)) &&
        (this.url == null ? job.url == null : this.url.equals(job.url)) &&
        (this.createdAt == null ? job.createdAt == null : this.createdAt.equals(job.createdAt)) &&
        (this.company == null ? job.company == null : this.company.equals(job.company)) &&
        (this.companyUrl == null ? job.companyUrl == null : this.companyUrl.equals(job.companyUrl)) &&
        (this.location == null ? job.location == null : this.location.equals(job.location)) &&
        (this.title == null ? job.title == null : this.title.equals(job.title)) &&
        (this.description == null ? job.description == null : this.description.equals(job.description)) &&
        (this.howToApply == null ? job.howToApply == null : this.howToApply.equals(job.howToApply)) &&
        (this.companyLogo == null ? job.companyLogo == null : this.companyLogo.equals(job.companyLogo));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.type == null ? 0: this.type.hashCode());
    result = 31 * result + (this.url == null ? 0: this.url.hashCode());
    result = 31 * result + (this.createdAt == null ? 0: this.createdAt.hashCode());
    result = 31 * result + (this.company == null ? 0: this.company.hashCode());
    result = 31 * result + (this.companyUrl == null ? 0: this.companyUrl.hashCode());
    result = 31 * result + (this.location == null ? 0: this.location.hashCode());
    result = 31 * result + (this.title == null ? 0: this.title.hashCode());
    result = 31 * result + (this.description == null ? 0: this.description.hashCode());
    result = 31 * result + (this.howToApply == null ? 0: this.howToApply.hashCode());
    result = 31 * result + (this.companyLogo == null ? 0: this.companyLogo.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Job {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  type: ").append(type).append("\n");
    sb.append("  url: ").append(url).append("\n");
    sb.append("  createdAt: ").append(createdAt).append("\n");
    sb.append("  company: ").append(company).append("\n");
    sb.append("  companyUrl: ").append(companyUrl).append("\n");
    sb.append("  location: ").append(location).append("\n");
    sb.append("  title: ").append(title).append("\n");
    sb.append("  description: ").append(description).append("\n");
    sb.append("  howToApply: ").append(howToApply).append("\n");
    sb.append("  companyLogo: ").append(companyLogo).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
