sudo: false
language: android
dist: trusty
licenses:
  - '.+'
env:
  global:
    - ANDROID_API_LEVEL=29
    - ANDROID_EMULATOR_LEVEL=22
    - ANDROID_BUILD_TOOLS_VERSION=29.0.3
    - ANDROID_ABI=armeabi-v7a-android-17
    - ANDROID_TAG=google_apis
    - ADB_INSTALL_TIMEOUT=20
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - tools
    # - platform-tools

    # The BuildTools version used by your project
    - build-tools-29.0.3

    # The SDK version used to compile your project
    - android-29

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-x86-android-29
    - sys-img-armeabi-v7a-android-17

before_script:
  # Create and start emulator.
  - echo no | android create avd --force -n test -t "android-"$ANDROID_EMULATOR_LEVEL --abi $ANDROID_ABI --tag $ANDROID_TAG
  - emulator -avd test -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &